"""Stamp the build with version + git commit + date.

Run before packaging (build.bat / build_msi.bat / CI). It rewrites
``src/token_counter/_buildinfo.py`` with the current git short SHA and UTC date,
and regenerates ``version_info.txt`` (the Windows resource embedded in the .exe)
from the same version — so the packaged exe reports exactly which commit it came
from, and Properties -> Details shows the right name/version.

Safe to run anywhere; if git isn't available the SHA falls back to "unknown".
"""

from __future__ import annotations

import datetime
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILDINFO = ROOT / "src" / "token_counter" / "_buildinfo.py"
VERSION_INFO = ROOT / "version_info.txt"


def current_version() -> str:
    """Read VERSION from _buildinfo.py without importing the package."""
    text = BUILDINFO.read_text(encoding="utf-8")
    m = re.search(r'VERSION\s*=\s*"([^"]+)"', text)
    return m.group(1) if m else "0.1.0"


def git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except Exception:
        return "unknown"


def buildinfo_text(version: str, sha: str, built: str) -> str:
    return (
        '"""Build identity for Token Counter. Generated by tools/stamp_build.py."""\n\n'
        "from __future__ import annotations\n\n"
        f'VERSION = "{version}"\n'
        f'GIT_SHA = "{sha}"\n'
        f'BUILT_AT = "{built}"\n\n\n'
        "def build_string() -> str:\n"
        '    return f"{VERSION} ({GIT_SHA}, {BUILT_AT})"\n'
    )


def version_info_text(version: str) -> str:
    parts = (version.split(".") + ["0", "0", "0", "0"])[:4]
    nums = ", ".join(str(int(p) if p.isdigit() else 0) for p in parts)
    return f"""# Generated by tools/stamp_build.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({nums}), prodvers=({nums}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Token Counter'),
        StringStruct('FileDescription', 'Token Counter'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'TokenCounter'),
        StringStruct('OriginalFilename', 'TokenCounter.exe'),
        StringStruct('ProductName', 'Token Counter'),
        StringStruct('ProductVersion', '{version}'),
        StringStruct('LegalCopyright', 'Token Counter'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def main() -> int:
    version = current_version()
    sha = git_sha()
    built = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    BUILDINFO.write_text(buildinfo_text(version, sha, built), encoding="utf-8")
    VERSION_INFO.write_text(version_info_text(version), encoding="utf-8")
    print(f"stamped build: {version} ({sha}, {built})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
